/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package maselu;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.JOptionPane;
import static maselu.Productos.cantidad1;
import static maselu.Productos.cantidad2;
import static maselu.Productos.cantidad3;
import static maselu.Productos.cantidad4;
import static maselu.Productos.cantidad5;
import static maselu.Productos2.cantidad10;
import static maselu.Productos2.cantidad6;
import static maselu.Productos2.cantidad7;
import static maselu.Productos2.cantidad8;
import static maselu.Productos2.cantidad9;

/**
 *
 * @author santi
 */
public class Pagar extends javax.swing.JFrame {

    public static double prod1 = 45000, prod2 = 26000, prod3 = 28000, prod4 = 32000,
            prod5 = 40000, prod6 = 20000, prod7 = 35000, prod8 = 23000, prod9 = 31000, prod10 = 25500,
            tsubtotal, ivatotal, icatotal, retetotal, Total, desdes, descuento;
    public static double aumentodescuento = 0.0;
    public static double porcentaje = 0.0;
    public static String texto;
    Conectar cc = new Conectar();
    Connection cn = cc.Conexion();
    Statement st;
    ResultSet rs;
    public Pagar() {
        initComponents();
                this.setLocationRelativeTo(this);

        
        Productos cant = new Productos();
        Jcant1.setText(Integer.toString(cant.cantidad1));
        Jcant2.setText(Integer.toString(cant.cantidad2));
        Jcant3.setText(Integer.toString(cant.cantidad3));
        Jcant4.setText(Integer.toString(cant.cantidad4));        
        Jcant5.setText(Integer.toString(cant.cantidad5));
        Productos2 canti = new Productos2();
        Jcant6.setText(Integer.toString(canti.cantidad6));
        Jcant7.setText(Integer.toString(canti.cantidad7));
        Jcant8.setText(Integer.toString(canti.cantidad8));
        Jcant9.setText(Integer.toString(canti.cantidad9));
        Jcant10.setText(Integer.toString(canti.cantidad10));
        
        
        
        
        
      

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Jcant2 = new javax.swing.JLabel();
        Jcant10 = new javax.swing.JLabel();
        Jcant1 = new javax.swing.JLabel();
        Jcant3 = new javax.swing.JLabel();
        Jcant4 = new javax.swing.JLabel();
        Jcant5 = new javax.swing.JLabel();
        Jcant6 = new javax.swing.JLabel();
        Jcant7 = new javax.swing.JLabel();
        Jcant8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Jcant9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        sub2 = new javax.swing.JLabel();
        sub3 = new javax.swing.JLabel();
        sub4 = new javax.swing.JLabel();
        sub5 = new javax.swing.JLabel();
        sub6 = new javax.swing.JLabel();
        sub7 = new javax.swing.JLabel();
        sub8 = new javax.swing.JLabel();
        sub9 = new javax.swing.JLabel();
        sub10 = new javax.swing.JLabel();
        sub1 = new javax.swing.JLabel();
        pago = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        vuni2 = new javax.swing.JLabel();
        vuni3 = new javax.swing.JLabel();
        vuni4 = new javax.swing.JLabel();
        vuni5 = new javax.swing.JLabel();
        vuni6 = new javax.swing.JLabel();
        vuni7 = new javax.swing.JLabel();
        vuni8 = new javax.swing.JLabel();
        vuni9 = new javax.swing.JLabel();
        vuni10 = new javax.swing.JLabel();
        vuni1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        iva2 = new javax.swing.JLabel();
        iva3 = new javax.swing.JLabel();
        iva4 = new javax.swing.JLabel();
        iva5 = new javax.swing.JLabel();
        iva6 = new javax.swing.JLabel();
        iva7 = new javax.swing.JLabel();
        iva8 = new javax.swing.JLabel();
        iva9 = new javax.swing.JLabel();
        iva10 = new javax.swing.JLabel();
        iva1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        rete2 = new javax.swing.JLabel();
        rete3 = new javax.swing.JLabel();
        rete4 = new javax.swing.JLabel();
        rete5 = new javax.swing.JLabel();
        rete6 = new javax.swing.JLabel();
        rete7 = new javax.swing.JLabel();
        rete8 = new javax.swing.JLabel();
        rete9 = new javax.swing.JLabel();
        rete10 = new javax.swing.JLabel();
        rete1 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ica2 = new javax.swing.JLabel();
        ica3 = new javax.swing.JLabel();
        ica4 = new javax.swing.JLabel();
        ica5 = new javax.swing.JLabel();
        ica6 = new javax.swing.JLabel();
        ica7 = new javax.swing.JLabel();
        ica8 = new javax.swing.JLabel();
        ica9 = new javax.swing.JLabel();
        ica10 = new javax.swing.JLabel();
        ica1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        audes = new javax.swing.JLabel();
        factura = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        factu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ravie", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("INVENTARIO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Articulo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Camisa Polo Az.Oscuro          ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 150, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Camisa Polo rosado                    ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 130, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Camisa Polo Rojo                       ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 120, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Camisa Lacoste verde                  ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 150, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Camisa NIKE negra                     ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 130, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Camisa Polo azul bebe                 ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 150, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Camisa Polo azul                         ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 120, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Camisa Polo Blanco                     ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 130, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Camisa Polo Gris                        ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 120, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Cantidad");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        Jcant2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(Jcant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 70, 20));

        Jcant10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(Jcant10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 70, 20));

        Jcant1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(Jcant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 70, 20));

        Jcant3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(Jcant3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 70, 20));

        Jcant4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(Jcant4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 70, 20));

        Jcant5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(Jcant5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 70, 20));

        Jcant6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(Jcant6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 70, 20));

        Jcant7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(Jcant7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 70, 20));

        Jcant8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(Jcant8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 70, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Camisa Polo Amarillo             ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 140, -1));

        Jcant9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(Jcant9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 70, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Subtotal");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        sub2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(sub2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 80, 20));

        sub3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(sub3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 80, 20));

        sub4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(sub4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 80, 20));

        sub5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(sub5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 80, 20));

        sub6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(sub6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 80, 20));

        sub7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(sub7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 80, 20));

        sub8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(sub8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 80, 20));

        sub9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(sub9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 80, 20));

        sub10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(sub10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, 80, 20));

        sub1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(sub1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 80, 20));

        pago.setBackground(new java.awt.Color(204, 0, 0));
        pago.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pago.setForeground(new java.awt.Color(255, 255, 255));
        pago.setText("Calcular");
        pago.setBorder(null);
        pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagoActionPerformed(evt);
            }
        });
        jPanel1.add(pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, 130, 50));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("V. Unidad");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        vuni2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(vuni2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 80, 20));

        vuni3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(vuni3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 80, 20));

        vuni4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(vuni4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 80, 20));

        vuni5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(vuni5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 80, 20));

        vuni6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(vuni6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 80, 20));

        vuni7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(vuni7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 80, 20));

        vuni8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(vuni8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 80, 20));

        vuni9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(vuni9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 80, 20));

        vuni10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(vuni10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 80, 20));

        vuni1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(vuni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 80, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("IVA");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, -1, -1));

        iva2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(iva2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 80, 20));

        iva3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(iva3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 80, 20));

        iva4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(iva4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 80, 20));

        iva5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(iva5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 80, 20));

        iva6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(iva6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 80, 20));

        iva7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(iva7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 80, 20));

        iva8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(iva8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 80, 20));

        iva9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(iva9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, 80, 20));

        iva10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(iva10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 80, 20));

        iva1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(iva1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 80, 20));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Retefuente");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, -1, -1));

        rete2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(rete2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 80, 20));

        rete3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(rete3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 80, 20));

        rete4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(rete4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 80, 20));

        rete5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(rete5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, 80, 20));

        rete6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(rete6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 80, 20));

        rete7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(rete7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 80, 20));

        rete8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(rete8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 80, 20));

        rete9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(rete9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, 80, 20));

        rete10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(rete10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, 80, 20));

        rete1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(rete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 80, 20));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("ICA");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, -1, -1));

        ica2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(ica2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 80, 20));

        ica3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(ica3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 80, 20));

        ica4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(ica4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 80, 20));

        ica5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(ica5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 80, 20));

        ica6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(ica6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 80, 20));

        ica7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(ica7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, 80, 20));

        ica8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(ica8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, 80, 20));

        ica9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(ica9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, 80, 20));

        ica10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(ica10, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 460, 80, 20));

        ica1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.add(ica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 100, 80, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("TOTAL A PAGAR =");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, -1, -1));

        total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 500, 160, 30));

        jButton1.setText("Firmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, -1, -1));

        audes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(audes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 340, 80));

        factura.setBackground(new java.awt.Color(0, 0, 204));
        factura.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        factura.setForeground(new java.awt.Color(255, 255, 255));
        factura.setText("Facturar");
        factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturaActionPerformed(evt);
            }
        });
        jPanel1.add(factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 550, 120, 50));

        jButton2.setText("Inicio");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, -1, -1));
        jPanel1.add(factu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagoActionPerformed
    
        
       



//Calculo de los subtotales de los prodcutos del 1er frame
        
        Productos multi = new Productos();
        double subtotal1 = prod1*multi.cantidad1;        
        sub1.setText(Double.toString(subtotal1));        
        double subtotal2 = prod2*multi.cantidad2;
        sub2.setText(Double.toString(subtotal2));        
        double subtotal3 = prod3 * multi.cantidad3;
        sub3.setText(Double.toString(subtotal3));        
        double subtotal4 = prod4 * multi.cantidad4;
        sub4.setText(Double.toString(subtotal4));        
        double subtotal5 = prod5 * multi.cantidad5;
        sub5.setText(Double.toString(subtotal5));
        
             
        
        
        //Calculo de el valor unitario de los productos del frame1
        if (multi.cantidad1 > 0){
            double vunitario1 = prod1*1;
            vuni1.setText(Double.toString(vunitario1));
        }else{
        vuni1.setText("0");
        }
        if (multi.cantidad2 > 0){
            double vunitario2 = prod2*1;
            vuni2.setText(Double.toString(vunitario2));
        }else{
        vuni2.setText("0");
        }
        if (multi.cantidad3 > 0){
            double vunitario3 = prod3*1;
            vuni3.setText(Double.toString(vunitario3));
        }else{
        vuni3.setText("0");
        }
        if (multi.cantidad4 > 0){
            double vunitario4 = prod4*1;
            vuni4.setText(Double.toString(vunitario4));
        }else{
        vuni4.setText("0");
        }
        if (multi.cantidad5 > 0){
            double vunitario5 = prod5*1;
            vuni5.setText(Double.toString(vunitario5));
        }else{
        vuni5.setText("0");                

        
        
        }
        //Calculo del IVA de los productos del frame1
        double ivaprod1 = (subtotal1 * 0.19);
        iva1.setText(Double.toString(ivaprod1));
         double ivaprod2 = (subtotal2 * 0.19);
        iva2.setText(Double.toString(ivaprod2));
         double ivaprod3 = (subtotal3 * 0.19);
        iva3.setText(Double.toString(ivaprod3));
         double ivaprod4 = (subtotal4 * 0.19);
        iva4.setText(Double.toString(ivaprod4));
         double ivaprod5 = (subtotal5 * 0.19);
        iva5.setText(Double.toString(ivaprod5));
        
        
        
        
         //Calculo del Retefuente de los productos del frame1
        double reteprod1 = (subtotal1 * 0.04);
        rete1.setText(Double.toString(reteprod1));
         double reteprod2 = (subtotal2 * 0.04);
        rete2.setText(Double.toString(reteprod2));
         double reteprod3 = (subtotal3 * 0.04);
        rete3.setText(Double.toString(reteprod3));
         double reteprod4 = (subtotal4 * 0.04);
        rete4.setText(Double.toString(reteprod4));
         double reteprod5 = (subtotal5 * 0.04);
        rete5.setText(Double.toString(reteprod5));
        
         //Calculo del ICA de los productos del 6 al 10
        double icaprod1 = (subtotal1 * (9.66/1000));
        ica1.setText(Double.toString(icaprod1));
         double icaprod2 = (subtotal2 * (9.66/1000));
        ica2.setText(Double.toString(icaprod2));
         double icaprod3 = (subtotal3 * (9.66/1000));
        ica3.setText(Double.toString(icaprod3));
         double icaprod4 = (subtotal4 * (9.66/1000));
        ica4.setText(Double.toString(icaprod4));
         double icaprod5 = (subtotal5 * (9.66/1000));
        ica5.setText(Double.toString(icaprod5));
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        //Calculo de los subtotales de los prodcutos del 2do frame
        Productos2 multip = new Productos2();
        double subtotal6 = prod6 * multip.cantidad6;
        sub6.setText(Double.toString(subtotal6));
        
        double subtotal7 = prod7 * multip.cantidad7;
        sub7.setText(Double.toString(subtotal7));
        
        double subtotal8 = prod8 * multip.cantidad8;
        sub8.setText(Double.toString(subtotal8));
        
        double subtotal9 = prod9 * multip.cantidad9;
        sub9.setText(Double.toString(subtotal9));
        
        double subtotal10 = prod10 * multip.cantidad10;
        sub10.setText(Double.toString(subtotal10));
        
        //Calculo de el valor unitario de los productos del frame2
        if (multip.cantidad6 > 0){
            double vunitario6 = prod6*1;
            vuni6.setText(Double.toString(vunitario6));
        }else{
        vuni6.setText("0");
        }
        if (multip.cantidad6 > 0){
            double vunitario6 = prod6*1;
            vuni6.setText(Double.toString(vunitario6));
        }else{
        vuni6.setText("0");
        }
        if (multip.cantidad7 > 0){
            double vunitario7 = prod7*1;
            vuni7.setText(Double.toString(vunitario7));
        }else{
        vuni7.setText("0");
        }if (multip.cantidad8 > 0){
            double vunitario8 = prod8*1;
            vuni8.setText(Double.toString(vunitario8));
        }else{
        vuni8.setText("0");
        }
        if (multip.cantidad9 > 0){
            double vunitario9 = prod9*1;
            vuni9.setText(Double.toString(vunitario9));
        }else{
        vuni9.setText("0");
        }
        if (multip.cantidad10 > 0){
            double vunitario10 = prod10*1;
            vuni10.setText(Double.toString(vunitario10));
        }else{
        vuni10.setText("0");
        }
        
        //Calculo del IVA de los productos del frame2
        double ivaprod6 = (subtotal6 * 0.19);
        iva6.setText(Double.toString(ivaprod6));
         double ivaprod7 = (subtotal7 * 0.19);
        iva7.setText(Double.toString(ivaprod7));
         double ivaprod8 = (subtotal8 * 0.19);
        iva8.setText(Double.toString(ivaprod8));
         double ivaprod9 = (subtotal9 * 0.19);
        iva9.setText(Double.toString(ivaprod9));
         double ivaprod10 = (subtotal10 * 0.19);
        iva10.setText(Double.toString(ivaprod10));
        
        //Calculo del Retefuente de los productos del frame2
        double reteprod6 = (subtotal6 * 0.04);
        rete6.setText(Double.toString(reteprod6));
         double reteprod7 = (subtotal7 * 0.04);
        rete7.setText(Double.toString(reteprod7));
         double reteprod8 = (subtotal8 * 0.04);
        rete8.setText(Double.toString(reteprod8));
         double reteprod9 = (subtotal9 * 0.04);
        rete9.setText(Double.toString(reteprod9));
         double reteprod10 = (subtotal10 * 0.04);
        rete10.setText(Double.toString(reteprod10));
        
        //Calculo del ICA de los productos del 6 al 10
        double icaprod6 = (subtotal6 * (9.66/1000));
        ica6.setText(Double.toString(icaprod6));
         double icaprod7 = (subtotal7 * (9.66/1000));
        ica7.setText(Double.toString(icaprod7));
         double icaprod8 = (subtotal8 * (9.66/1000));
        ica8.setText(Double.toString(icaprod8));
         double icaprod9 = (subtotal9 * (9.66/1000));
        ica9.setText(Double.toString(icaprod9));
         double icaprod10 = (subtotal10 * (9.66/1000));
        ica10.setText(Double.toString(icaprod10));                      
        
        //Generar advertencia de no haber productos                 
          if(cantidad1==0&&cantidad2==0&&cantidad3==0&&cantidad4==0&&cantidad5==0
                && cantidad6==0&&cantidad7==0&&cantidad8==0&&cantidad9==0&&cantidad10==0){
            JOptionPane.showMessageDialog(null, "No hay articulos para pagar" );                
        }
          
        
        
        
        
        
        
        
        
          tsubtotal= subtotal1 +subtotal2 + subtotal3 + subtotal4 + subtotal5 
                  + subtotal6 + subtotal7 + subtotal8+subtotal9 + subtotal10;
        System.out.println("tsubtotal "+tsubtotal); 
        
        ivatotal = ivaprod1 + ivaprod2 + ivaprod3 + ivaprod4 + ivaprod5+
                    ivaprod6+ivaprod7+ivaprod8+ivaprod9+ivaprod10;
        System.out.println("ivatotal " +ivatotal);
        
        retetotal = reteprod1+reteprod2+reteprod3+reteprod4+reteprod5+
                reteprod6+reteprod7+reteprod8+reteprod9+reteprod10;
        System.out.println("Retefuente total " +retetotal);
        
        icatotal = icaprod1+icaprod2+icaprod3+icaprod5+icaprod6+icaprod7+icaprod8+icaprod9+icaprod10;
        System.out.println("ica total " +icatotal);
        
       
        System.out.println("total " +total);
        //Generar valor de descuento o aumento 
            Random num = new Random();
            int numale = num.nextInt(10);
            System.out.println("numero aleatorio" +numale);
            
            double descuento10 =0.10;
            double descuento20 =0.20;   
            double descuento50 =0.50;
            double aumento10 = 0.10;
            double aumento20 = 0.20;
          
            
            if(numale==0 || numale ==1){
                porcentaje = descuento10 * 100;
                aumentodescuento = tsubtotal *(1-descuento10);
                audes.setText("SU DESCUENTO FUE DEL:" +porcentaje+"%");
            }else if (numale==2 || numale ==3){
                porcentaje = descuento20 * 100;
                aumentodescuento = tsubtotal * (1-descuento20);
                 audes.setText("SU DESCUENTO FUE DEL:" +porcentaje+"%");
            }else if(numale==4 || numale ==5){
                porcentaje = descuento50 * 100;
                aumentodescuento = tsubtotal* (1- descuento50);
                 audes.setText("SU DESCUENTO FUE DEL:" +porcentaje+"%");
            }else if(numale==6 || numale ==7){
                porcentaje = aumento20 * 100;
                aumentodescuento = tsubtotal*(1+aumento20);
                 audes.setText("SU AUMENTO FUE DEL:" +porcentaje+"%");
            }else{
                aumentodescuento = tsubtotal *(1+aumento10);
                porcentaje = aumento10 * 100;
                 audes.setText("SU AUMENTO FUE DEL:" +porcentaje+"%");
            }
                                    
         Total= aumentodescuento + ivatotal - retetotal - icatotal;
        String total2d = String.format("%.2f", Total);
        texto = audes.getText();
        desdes = tsubtotal-aumentodescuento; 
         descuento= desdes;
         descuento*=-1;
        
        
        total.setText( String.format("%.2f", Total));
       
        
        
        
        
        
        
        
        
       
    }//GEN-LAST:event_pagoActionPerformed

    private void facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturaActionPerformed
         Firmas s = new Firmas ();       
         if (!s.firmasiono) {
        JOptionPane.showMessageDialog(null, "Por favor, firme antes de continuar.", "Firma requerida", JOptionPane.WARNING_MESSAGE);
        return; // Detiene la ejecución del método si la firma no se ha realizado
    }
        
        
        
        
        
        
        Factura abrir = new Factura();
                abrir.setVisible(true);
                this.setVisible(false);
                Insertar();
               
     
        
        if(cantidad1==0&&cantidad2==0&&cantidad3==0&&cantidad4==0&&cantidad5==0
                && cantidad6==0&&cantidad7==0&&cantidad8==0&&cantidad9==0&&cantidad10==0){
            JOptionPane.showMessageDialog(null, "No hay articulos para facturar");             
                                    
        }
       
        
        
    }//GEN-LAST:event_facturaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Firmas abrir = new Firmas();
         abrir.setVisible(true);
       
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Productos abrir = new Productos ();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pagar().setVisible(true);
            }
        });
    }
    
        void Insertar(){
        Firmas m = new Firmas();
   // String id= factu.getText();     
    String nom= m.nombre;    
    String ape = m.apellido;
    String ced= Integer.toString(m.documento); 
    String tel = Long.toString(m.telefono);
    String correo= m.email;
    Factura l = new Factura();
    String p1= Double.toString(l.subtotal1);
    String p2= Double.toString(l.subtotal2);
    String p3= Double.toString(l.subtotal3);
    String p4= Double.toString(l.subtotal4);
    String p5= Double.toString(l.subtotal5);
    String p6= Double.toString(l.subtotal6);
    String p7= Double.toString(l.subtotal7);
    String p8= Double.toString(l.subtotal8);
    String p9= Double.toString(l.subtotal9);
    String p10= Double.toString(l.subtotal10);
    Pagar s = new Pagar();
    String subt = Double.toString(s.tsubtotal);
    String iva= Double.toString(s.ivatotal);
    String ica= Double.toString(s.icatotal);
    String rete= Double.toString(s.retetotal);
    String desa= Double.toString(s.descuento);
    String total=Double.toString(s.Total);
    
    String date= java.time.LocalDate.now().toString();
      
    String sql = "INSERT INTO maselu (Nombre, Apellido, Cedula, Telefono, Correo, "
            + "P1, P2, P3, P4, P5, P6, P7, P8, P9, P10, "
            + "Subtotal, IVA, ICA, Retefuente, AUOD, Fecha, Total)"
            + " VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";      
    try{
    PreparedStatement pst = (PreparedStatement) cn.prepareStatement(sql);
    
   // pst.setString(1, id);
    pst.setString(1, nom);
    pst.setString(2, ape);
    pst.setString(3, ced);
    pst.setString(4, tel);
    pst.setString(5, correo);
    pst.setString(6, p1);
    pst.setString(7, p2);
    pst.setString(8, p3);
    pst.setString(9, p4);
    pst.setString(10, p5);
    pst.setString(11, p6);
    pst.setString(12, p7);
    pst.setString(13, p8);
    pst.setString(14, p9);
    pst.setString(15, p10);
    pst.setString(16, subt);
    pst.setString(17, iva);
    pst.setString(18, ica);
    pst.setString(19, rete);
    pst.setString(20, desa);
    pst.setString(21,  (date));
    pst.setString(22, total);
    pst.executeUpdate();
    cn.commit();
        JOptionPane.showMessageDialog(null, "Datos insertados correctamente");
    }catch(Exception e){
                e.printStackTrace();

    
    }              
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jcant1;
    private javax.swing.JLabel Jcant10;
    private javax.swing.JLabel Jcant2;
    private javax.swing.JLabel Jcant3;
    private javax.swing.JLabel Jcant4;
    private javax.swing.JLabel Jcant5;
    private javax.swing.JLabel Jcant6;
    private javax.swing.JLabel Jcant7;
    private javax.swing.JLabel Jcant8;
    private javax.swing.JLabel Jcant9;
    private javax.swing.JLabel audes;
    private javax.swing.JLabel factu;
    private javax.swing.JButton factura;
    private javax.swing.JLabel ica1;
    private javax.swing.JLabel ica10;
    private javax.swing.JLabel ica2;
    private javax.swing.JLabel ica3;
    private javax.swing.JLabel ica4;
    private javax.swing.JLabel ica5;
    private javax.swing.JLabel ica6;
    private javax.swing.JLabel ica7;
    private javax.swing.JLabel ica8;
    private javax.swing.JLabel ica9;
    private javax.swing.JLabel iva1;
    private javax.swing.JLabel iva10;
    private javax.swing.JLabel iva2;
    private javax.swing.JLabel iva3;
    private javax.swing.JLabel iva4;
    private javax.swing.JLabel iva5;
    private javax.swing.JLabel iva6;
    private javax.swing.JLabel iva7;
    private javax.swing.JLabel iva8;
    private javax.swing.JLabel iva9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pago;
    private javax.swing.JLabel rete1;
    private javax.swing.JLabel rete10;
    private javax.swing.JLabel rete2;
    private javax.swing.JLabel rete3;
    private javax.swing.JLabel rete4;
    private javax.swing.JLabel rete5;
    private javax.swing.JLabel rete6;
    private javax.swing.JLabel rete7;
    private javax.swing.JLabel rete8;
    private javax.swing.JLabel rete9;
    private javax.swing.JLabel sub1;
    private javax.swing.JLabel sub10;
    private javax.swing.JLabel sub2;
    private javax.swing.JLabel sub3;
    private javax.swing.JLabel sub4;
    private javax.swing.JLabel sub5;
    private javax.swing.JLabel sub6;
    private javax.swing.JLabel sub7;
    private javax.swing.JLabel sub8;
    private javax.swing.JLabel sub9;
    private javax.swing.JLabel total;
    private javax.swing.JLabel vuni1;
    private javax.swing.JLabel vuni10;
    private javax.swing.JLabel vuni2;
    private javax.swing.JLabel vuni3;
    private javax.swing.JLabel vuni4;
    private javax.swing.JLabel vuni5;
    private javax.swing.JLabel vuni6;
    private javax.swing.JLabel vuni7;
    private javax.swing.JLabel vuni8;
    private javax.swing.JLabel vuni9;
    // End of variables declaration//GEN-END:variables
}
