/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package maselu;

import java.awt.Image;
import java.awt.event.MouseAdapter;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.awt.*;
import java.awt.event.*;
import javax.swing.JOptionPane;
import static maselu.Productos2.cantidad10;
import static maselu.Productos2.cantidad6;
import static maselu.Productos2.cantidad7;
import static maselu.Productos2.cantidad8;
import static maselu.Productos2.cantidad9;

/**
 *
 * @author santi
 */
public class Productos extends javax.swing.JFrame {
   public static int cantidad1, cantidad2, cantidad3, cantidad4, cantidad5; 
   public static String PoloNegra;
    
    private ImageIcon imagen;
    private Icon icono;
    public Productos() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.pintarImagen(this.prod1, "src/maselu/polo negra.jpg");
        this.pintarImagen(this.prod5, "src/maselu/poloverde.jpg");
        this.pintarImagen(this.prod2, "src/maselu/polorojo.jpg");
        this.pintarImagen(this.prod3, "src/maselu/poloblanco.jpg");
        this.pintarImagen(this.prod4, "src/maselu/pologris.jpg");
        
        
       
     

       prod1.addMouseListener(new MouseAdapter() {
    @Override
    public void mouseClicked(MouseEvent e) {
        
        int cantidad = Integer.parseInt(cant1.getText());
        cantidad++; // Incrementar la cantidad
        cant1.setText(String.valueOf(cantidad)); // Actualizar el campo de texto
                 cantidad1 = Integer.parseInt(cant1.getText());

    }
});
       prod2.addMouseListener(new MouseAdapter() {
    @Override
    public void mouseClicked(MouseEvent e) {
        int cantidad = Integer.parseInt(cant2.getText());
        cantidad++; // Incrementar la cantidad
        cant2.setText(String.valueOf(cantidad)); // Actualizar el campo de texto
                cantidad2= Integer.parseInt(cant2.getText());

    }
});
       prod3.addMouseListener(new MouseAdapter() {
    @Override
    public void mouseClicked(MouseEvent e) {
        int cantidad = Integer.parseInt(cant3.getText());
        cantidad++; // Incrementar la cantidad
        cant3.setText(String.valueOf(cantidad)); // Actualizar el campo de texto
                cantidad3 = Integer.parseInt(cant3.getText());

    }
});
       prod4.addMouseListener(new MouseAdapter() {
    @Override
    public void mouseClicked(MouseEvent e) {
        int cantidad = Integer.parseInt(cant4.getText());
        cantidad++; // Incrementar la cantidad
        cant4.setText(String.valueOf(cantidad)); // Actualizar el campo de texto
                cantidad4 = Integer.parseInt(cant4.getText());

    }
});
       prod5.addMouseListener(new MouseAdapter() {
    @Override
    public void mouseClicked(MouseEvent e) {
        int cantidad = Integer.parseInt(cant5.getText());
        cantidad++; // Incrementar la cantidad
        cant5.setText(String.valueOf(cantidad)); // Actualizar el campo de texto
                        cantidad5 = Integer.parseInt(cant5.getText());

    }
});

        cant1.setText(Integer.toString(cantidad1));
        cant2.setText(Integer.toString(cantidad2));
        cant3.setText(Integer.toString(cantidad3));
        cant4.setText(Integer.toString(cantidad4));
        cant5.setText(Integer.toString(cantidad5));

                                   
       

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        prod1 = new javax.swing.JLabel();
        prod5 = new javax.swing.JLabel();
        prod2 = new javax.swing.JLabel();
        prod3 = new javax.swing.JLabel();
        prod4 = new javax.swing.JLabel();
        cant1 = new javax.swing.JTextField();
        resprod1 = new javax.swing.JButton();
        sumprod1 = new javax.swing.JButton();
        cant2 = new javax.swing.JTextField();
        resprod2 = new javax.swing.JButton();
        sumprod2 = new javax.swing.JButton();
        cant3 = new javax.swing.JTextField();
        resprod3 = new javax.swing.JButton();
        sumprod3 = new javax.swing.JButton();
        cant4 = new javax.swing.JTextField();
        resprod4 = new javax.swing.JButton();
        sumprod4 = new javax.swing.JButton();
        cant5 = new javax.swing.JTextField();
        resprod5 = new javax.swing.JButton();
        sumprod5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ravie", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("MASELU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 350, 60));

        jButton1.setText("PAG 2");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 580, -1, -1));

        prod1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(prod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 130, 130));

        prod5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(prod5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 130, 130));

        prod2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(prod2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 130, 130));

        prod3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(prod3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 130, 130));

        prod4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(prod4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 130, 130));

        cant1.setEditable(false);
        cant1.setBackground(new java.awt.Color(255, 255, 255));
        cant1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cant1.setText("0");
        cant1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cant1ActionPerformed(evt);
            }
        });
        jPanel1.add(cant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 40, 30));

        resprod1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        resprod1.setText("-");
        resprod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resprod1ActionPerformed(evt);
            }
        });
        jPanel1.add(resprod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 40, 30));

        sumprod1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sumprod1.setText("+");
        sumprod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumprod1ActionPerformed(evt);
            }
        });
        jPanel1.add(sumprod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 40, 30));

        cant2.setEditable(false);
        cant2.setBackground(new java.awt.Color(255, 255, 255));
        cant2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cant2.setText("0");
        cant2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cant2ActionPerformed(evt);
            }
        });
        jPanel1.add(cant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 40, 30));

        resprod2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        resprod2.setText("-");
        resprod2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resprod2ActionPerformed(evt);
            }
        });
        jPanel1.add(resprod2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 40, 30));

        sumprod2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sumprod2.setText("+");
        sumprod2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumprod2ActionPerformed(evt);
            }
        });
        jPanel1.add(sumprod2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 40, 30));

        cant3.setEditable(false);
        cant3.setBackground(new java.awt.Color(255, 255, 255));
        cant3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cant3.setText("0");
        jPanel1.add(cant3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 40, 30));

        resprod3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        resprod3.setText("-");
        resprod3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resprod3ActionPerformed(evt);
            }
        });
        jPanel1.add(resprod3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 40, 30));

        sumprod3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sumprod3.setText("+");
        sumprod3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumprod3ActionPerformed(evt);
            }
        });
        jPanel1.add(sumprod3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 40, 30));

        cant4.setEditable(false);
        cant4.setBackground(new java.awt.Color(255, 255, 255));
        cant4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cant4.setText("0");
        jPanel1.add(cant4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 40, 30));

        resprod4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        resprod4.setText("-");
        resprod4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resprod4ActionPerformed(evt);
            }
        });
        jPanel1.add(resprod4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 40, 30));

        sumprod4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sumprod4.setText("+");
        sumprod4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumprod4ActionPerformed(evt);
            }
        });
        jPanel1.add(sumprod4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 40, 30));

        cant5.setEditable(false);
        cant5.setBackground(new java.awt.Color(255, 255, 255));
        cant5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cant5.setText("0");
        jPanel1.add(cant5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 40, 30));

        resprod5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        resprod5.setText("-");
        resprod5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resprod5ActionPerformed(evt);
            }
        });
        jPanel1.add(resprod5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 40, 30));

        sumprod5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sumprod5.setText("+");
        sumprod5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumprod5ActionPerformed(evt);
            }
        });
        jPanel1.add(sumprod5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 40, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setText("Camisa Polo Rojo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setText("Camisa Polo Blanca");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setText("Camisa Polo Gris");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setText("Camisa Lacoste Verde");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setText("Camisa NIKE Negra");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jButton2.setText("Catálogo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jButton3.setText("PAGAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 580, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Productos2 abrir = new Productos2();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sumprod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumprod1ActionPerformed
        int cantidad = Integer.parseInt(cant1.getText());
        cant1.setText(String.valueOf(cantidad+1));
         cantidad1 = Integer.parseInt(cant1.getText());
        
    }//GEN-LAST:event_sumprod1ActionPerformed

    private void sumprod2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumprod2ActionPerformed
        int cantidad = Integer.parseInt(cant2.getText());        
        String resultado = String.valueOf(suma(cantidad));        
        cant2.setText(resultado);
        cantidad2= Integer.parseInt(cant2.getText());
    }//GEN-LAST:event_sumprod2ActionPerformed

    private void sumprod3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumprod3ActionPerformed
        int cantidad = Integer.parseInt(cant3.getText());        
        String resultado = String.valueOf(suma(cantidad));        
        cant3.setText(resultado);
        cantidad3 = Integer.parseInt(cant3.getText());
    }//GEN-LAST:event_sumprod3ActionPerformed

    private void sumprod4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumprod4ActionPerformed
              int cantidad = Integer.parseInt(cant4.getText());
        String resultado = String.valueOf(suma(cantidad));        
        cant4.setText(resultado);
        cantidad4 = Integer.parseInt(cant4.getText());
    }//GEN-LAST:event_sumprod4ActionPerformed

    private void sumprod5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumprod5ActionPerformed
        int cantidad = Integer.parseInt(cant5.getText());        
        String resultado = String.valueOf(suma(cantidad));        
        cant5.setText(resultado);
        cantidad5 = Integer.parseInt(cant5.getText());
    }//GEN-LAST:event_sumprod5ActionPerformed

    private void resprod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resprod1ActionPerformed
         int cantidad = Integer.parseInt(cant1.getText());        
        String resultado = String.valueOf(resta(cantidad));        
        cant1.setText(resultado); 
                 cantidad1 = Integer.parseInt(cant1.getText());

    }//GEN-LAST:event_resprod1ActionPerformed

    private void resprod2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resprod2ActionPerformed
        int cantidad = Integer.parseInt(cant2.getText());        
        String resultado = String.valueOf(resta(cantidad));                
        cant2.setText(resultado);
                cantidad2= Integer.parseInt(cant2.getText());

    }//GEN-LAST:event_resprod2ActionPerformed

    private void resprod3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resprod3ActionPerformed
 int cantidad = Integer.parseInt(cant3.getText());        
        String resultado = String.valueOf(resta(cantidad));        
        cant3.setText(resultado);
                cantidad3 = Integer.parseInt(cant3.getText());

    }//GEN-LAST:event_resprod3ActionPerformed

    private void resprod4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resprod4ActionPerformed
 int cantidad = Integer.parseInt(cant4.getText());        
        String resultado = String.valueOf(resta(cantidad));        
        cant4.setText(resultado);
                cantidad4 = Integer.parseInt(cant4.getText());

    }//GEN-LAST:event_resprod4ActionPerformed

    private void resprod5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resprod5ActionPerformed
         int cantidad = Integer.parseInt(cant5.getText());
        String resultado = String.valueOf(resta(cantidad));        
        cant5.setText(resultado);
                cantidad5 = Integer.parseInt(cant5.getText());

    }//GEN-LAST:event_resprod5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Catalogo abrir = new Catalogo();
        abrir.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Pagar abrir = new Pagar();
        abrir.setVisible(true);
        this.setVisible(false);
       Productos adv = new Productos ();
        if(adv.cantidad1==0&&adv.cantidad2==0&&adv.cantidad3==0&&adv.cantidad4==0&&adv.cantidad5==0
                && cantidad6==0&&cantidad7==0&&cantidad8==0&&cantidad9==0&&cantidad10==0){
            JOptionPane.showMessageDialog(null, "No hay articulos para pagar");
        }
        
        Factura l = new Factura();
        l.reiniciar();
       
     
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cant1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cant1ActionPerformed
        
   
    }//GEN-LAST:event_cant1ActionPerformed

    private void cant2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cant2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cant2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }
 private void pintarImagen( JLabel lbl, String ruta) {
        this.imagen= new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage()
                        .getScaledInstance(
                                lbl.getWidth(),
                                lbl.getHeight(),
                                Image.SCALE_DEFAULT));
        lbl.setIcon(this.icono);
        this.repaint();
    }
        private int suma ( int cantidad){
            cantidad = cantidad +1;
            return cantidad;        
        }
        private int resta (int cantidad){
        if(cantidad>0){
            cantidad = cantidad-1;
        }
        return cantidad;
        }
        public void reiniciocant(){                               
        cantidad1 = 0;
        cant1.setText(Integer.toString(cantidad1));
        cantidad2 = 0;
        cant2.setText(Integer.toString(cantidad2));
        cantidad3 = 0;
        cant3.setText(Integer.toString(cantidad3));
        cantidad4 = 0;
        cant4.setText(Integer.toString(cantidad4)); 
        cantidad5 = 0;
        cant5.setText(Integer.toString(cantidad5));
        
        }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cant1;
    private javax.swing.JTextField cant2;
    private javax.swing.JTextField cant3;
    private javax.swing.JTextField cant4;
    private javax.swing.JTextField cant5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel prod1;
    private javax.swing.JLabel prod2;
    private javax.swing.JLabel prod3;
    private javax.swing.JLabel prod4;
    private javax.swing.JLabel prod5;
    private javax.swing.JButton resprod1;
    private javax.swing.JButton resprod2;
    private javax.swing.JButton resprod3;
    private javax.swing.JButton resprod4;
    private javax.swing.JButton resprod5;
    private javax.swing.JButton sumprod1;
    private javax.swing.JButton sumprod2;
    private javax.swing.JButton sumprod3;
    private javax.swing.JButton sumprod4;
    private javax.swing.JButton sumprod5;
    // End of variables declaration//GEN-END:variables
}
